name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Mandatory : fetch the current repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Environment for PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          #extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Test
        run: php bin/phpunit
